/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventRegisterRouteImport } from './routes/event-register'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedConsentVideoRouteImport } from './routes/_authenticated.consent.video'
import { Route as AuthenticatedConsentEducationRouteImport } from './routes/_authenticated.consent.education'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated.admin.videos'
import { Route as AuthenticatedAdminRisksRouteImport } from './routes/_authenticated.admin.risks'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated.admin.reports'
import { Route as AuthenticatedAdminPiiEncryptionBackfillRouteImport } from './routes/_authenticated.admin.pii-encryption-backfill'
import { Route as AuthenticatedAdminMyDataRouteImport } from './routes/_authenticated.admin.my-data'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated.admin.inventory'
import { Route as AuthenticatedAdminDprRouteImport } from './routes/_authenticated.admin.dpr'
import { Route as AuthenticatedAdminCorrectionsRouteImport } from './routes/_authenticated.admin.corrections'
import { Route as AuthenticatedAdminConsentRouteImport } from './routes/_authenticated.admin.consent'
import { Route as AuthenticatedAdminComplianceRouteImport } from './routes/_authenticated.admin.compliance'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated.admin.campaigns'
import { Route as AuthenticatedAdminBreachesRouteImport } from './routes/_authenticated.admin.breaches'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedAdminRequestsIndexRouteImport } from './routes/_authenticated.admin.requests.index'
import { Route as AuthenticatedAdminEmployeesIndexRouteImport } from './routes/_authenticated.admin.employees.index'
import { Route as AuthenticatedAdminRequestsIdRouteImport } from './routes/_authenticated.admin.requests.$id'
import { Route as AuthenticatedAdminEmployeesIdRouteImport } from './routes/_authenticated.admin.employees.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRegisterRoute = EventRegisterRouteImport.update({
  id: '/event-register',
  path: '/event-register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedConsentVideoRoute =
  AuthenticatedConsentVideoRouteImport.update({
    id: '/consent/video',
    path: '/consent/video',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsentEducationRoute =
  AuthenticatedConsentEducationRouteImport.update({
    id: '/consent/education',
    path: '/consent/education',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRisksRoute = AuthenticatedAdminRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPiiEncryptionBackfillRoute =
  AuthenticatedAdminPiiEncryptionBackfillRouteImport.update({
    id: '/pii-encryption-backfill',
    path: '/pii-encryption-backfill',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMyDataRoute =
  AuthenticatedAdminMyDataRouteImport.update({
    id: '/my-data',
    path: '/my-data',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDprRoute = AuthenticatedAdminDprRouteImport.update({
  id: '/dpr',
  path: '/dpr',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCorrectionsRoute =
  AuthenticatedAdminCorrectionsRouteImport.update({
    id: '/corrections',
    path: '/corrections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConsentRoute =
  AuthenticatedAdminConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComplianceRoute =
  AuthenticatedAdminComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBreachesRoute =
  AuthenticatedAdminBreachesRouteImport.update({
    id: '/breaches',
    path: '/breaches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRequestsIndexRoute =
  AuthenticatedAdminRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesIndexRoute =
  AuthenticatedAdminEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsIdRoute =
  AuthenticatedAdminRequestsIdRouteImport.update({
    id: '/requests/$id',
    path: '/requests/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesIdRoute =
  AuthenticatedAdminEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/event-register': typeof EventRegisterRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/breaches': typeof AuthenticatedAdminBreachesRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/admin/corrections': typeof AuthenticatedAdminCorrectionsRoute
  '/admin/dpr': typeof AuthenticatedAdminDprRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/my-data': typeof AuthenticatedAdminMyDataRoute
  '/admin/pii-encryption-backfill': typeof AuthenticatedAdminPiiEncryptionBackfillRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/risks': typeof AuthenticatedAdminRisksRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/consent/education': typeof AuthenticatedConsentEducationRoute
  '/consent/video': typeof AuthenticatedConsentVideoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/admin/employees/': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/requests/': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/event-register': typeof EventRegisterRoute
  '/login': typeof LoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/breaches': typeof AuthenticatedAdminBreachesRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/admin/corrections': typeof AuthenticatedAdminCorrectionsRoute
  '/admin/dpr': typeof AuthenticatedAdminDprRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/my-data': typeof AuthenticatedAdminMyDataRoute
  '/admin/pii-encryption-backfill': typeof AuthenticatedAdminPiiEncryptionBackfillRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/risks': typeof AuthenticatedAdminRisksRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/consent/education': typeof AuthenticatedConsentEducationRoute
  '/consent/video': typeof AuthenticatedConsentVideoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesIndexRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/event-register': typeof EventRegisterRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/breaches': typeof AuthenticatedAdminBreachesRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/_authenticated/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/_authenticated/admin/corrections': typeof AuthenticatedAdminCorrectionsRoute
  '/_authenticated/admin/dpr': typeof AuthenticatedAdminDprRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/my-data': typeof AuthenticatedAdminMyDataRoute
  '/_authenticated/admin/pii-encryption-backfill': typeof AuthenticatedAdminPiiEncryptionBackfillRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/risks': typeof AuthenticatedAdminRisksRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/consent/education': typeof AuthenticatedConsentEducationRoute
  '/_authenticated/consent/video': typeof AuthenticatedConsentVideoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/employees/$id': typeof AuthenticatedAdminEmployeesIdRoute
  '/_authenticated/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/_authenticated/admin/employees/': typeof AuthenticatedAdminEmployeesIndexRoute
  '/_authenticated/admin/requests/': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/event-register'
    | '/login'
    | '/admin'
    | '/invite/$token'
    | '/admin/audit'
    | '/admin/breaches'
    | '/admin/campaigns'
    | '/admin/compliance'
    | '/admin/consent'
    | '/admin/corrections'
    | '/admin/dpr'
    | '/admin/inventory'
    | '/admin/my-data'
    | '/admin/pii-encryption-backfill'
    | '/admin/reports'
    | '/admin/risks'
    | '/admin/videos'
    | '/consent/education'
    | '/consent/video'
    | '/admin/'
    | '/admin/employees/$id'
    | '/admin/requests/$id'
    | '/admin/employees/'
    | '/admin/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/event-register'
    | '/login'
    | '/invite/$token'
    | '/'
    | '/admin/audit'
    | '/admin/breaches'
    | '/admin/campaigns'
    | '/admin/compliance'
    | '/admin/consent'
    | '/admin/corrections'
    | '/admin/dpr'
    | '/admin/inventory'
    | '/admin/my-data'
    | '/admin/pii-encryption-backfill'
    | '/admin/reports'
    | '/admin/risks'
    | '/admin/videos'
    | '/consent/education'
    | '/consent/video'
    | '/admin'
    | '/admin/employees/$id'
    | '/admin/requests/$id'
    | '/admin/employees'
    | '/admin/requests'
  id:
    | '__root__'
    | '/_authenticated'
    | '/event-register'
    | '/login'
    | '/_authenticated/admin'
    | '/invite/$token'
    | '/_authenticated/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/breaches'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/compliance'
    | '/_authenticated/admin/consent'
    | '/_authenticated/admin/corrections'
    | '/_authenticated/admin/dpr'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/my-data'
    | '/_authenticated/admin/pii-encryption-backfill'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/risks'
    | '/_authenticated/admin/videos'
    | '/_authenticated/consent/education'
    | '/_authenticated/consent/video'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/employees/$id'
    | '/_authenticated/admin/requests/$id'
    | '/_authenticated/admin/employees/'
    | '/_authenticated/admin/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EventRegisterRoute: typeof EventRegisterRoute
  LoginRoute: typeof LoginRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-register': {
      id: '/event-register'
      path: '/event-register'
      fullPath: '/event-register'
      preLoaderRoute: typeof EventRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/consent/video': {
      id: '/_authenticated/consent/video'
      path: '/consent/video'
      fullPath: '/consent/video'
      preLoaderRoute: typeof AuthenticatedConsentVideoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consent/education': {
      id: '/_authenticated/consent/education'
      path: '/consent/education'
      fullPath: '/consent/education'
      preLoaderRoute: typeof AuthenticatedConsentEducationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/risks': {
      id: '/_authenticated/admin/risks'
      path: '/risks'
      fullPath: '/admin/risks'
      preLoaderRoute: typeof AuthenticatedAdminRisksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pii-encryption-backfill': {
      id: '/_authenticated/admin/pii-encryption-backfill'
      path: '/pii-encryption-backfill'
      fullPath: '/admin/pii-encryption-backfill'
      preLoaderRoute: typeof AuthenticatedAdminPiiEncryptionBackfillRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/my-data': {
      id: '/_authenticated/admin/my-data'
      path: '/my-data'
      fullPath: '/admin/my-data'
      preLoaderRoute: typeof AuthenticatedAdminMyDataRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dpr': {
      id: '/_authenticated/admin/dpr'
      path: '/dpr'
      fullPath: '/admin/dpr'
      preLoaderRoute: typeof AuthenticatedAdminDprRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/corrections': {
      id: '/_authenticated/admin/corrections'
      path: '/corrections'
      fullPath: '/admin/corrections'
      preLoaderRoute: typeof AuthenticatedAdminCorrectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/consent': {
      id: '/_authenticated/admin/consent'
      path: '/consent'
      fullPath: '/admin/consent'
      preLoaderRoute: typeof AuthenticatedAdminConsentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/compliance': {
      id: '/_authenticated/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AuthenticatedAdminComplianceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/breaches': {
      id: '/_authenticated/admin/breaches'
      path: '/breaches'
      fullPath: '/admin/breaches'
      preLoaderRoute: typeof AuthenticatedAdminBreachesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests/': {
      id: '/_authenticated/admin/requests/'
      path: '/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees/': {
      id: '/_authenticated/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests/$id': {
      id: '/_authenticated/admin/requests/$id'
      path: '/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees/$id': {
      id: '/_authenticated/admin/employees/$id'
      path: '/employees/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBreachesRoute: typeof AuthenticatedAdminBreachesRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminComplianceRoute: typeof AuthenticatedAdminComplianceRoute
  AuthenticatedAdminConsentRoute: typeof AuthenticatedAdminConsentRoute
  AuthenticatedAdminCorrectionsRoute: typeof AuthenticatedAdminCorrectionsRoute
  AuthenticatedAdminDprRoute: typeof AuthenticatedAdminDprRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminMyDataRoute: typeof AuthenticatedAdminMyDataRoute
  AuthenticatedAdminPiiEncryptionBackfillRoute: typeof AuthenticatedAdminPiiEncryptionBackfillRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRisksRoute: typeof AuthenticatedAdminRisksRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEmployeesIdRoute: typeof AuthenticatedAdminEmployeesIdRoute
  AuthenticatedAdminRequestsIdRoute: typeof AuthenticatedAdminRequestsIdRoute
  AuthenticatedAdminEmployeesIndexRoute: typeof AuthenticatedAdminEmployeesIndexRoute
  AuthenticatedAdminRequestsIndexRoute: typeof AuthenticatedAdminRequestsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBreachesRoute: AuthenticatedAdminBreachesRoute,
  AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
  AuthenticatedAdminComplianceRoute: AuthenticatedAdminComplianceRoute,
  AuthenticatedAdminConsentRoute: AuthenticatedAdminConsentRoute,
  AuthenticatedAdminCorrectionsRoute: AuthenticatedAdminCorrectionsRoute,
  AuthenticatedAdminDprRoute: AuthenticatedAdminDprRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminMyDataRoute: AuthenticatedAdminMyDataRoute,
  AuthenticatedAdminPiiEncryptionBackfillRoute:
    AuthenticatedAdminPiiEncryptionBackfillRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRisksRoute: AuthenticatedAdminRisksRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEmployeesIdRoute: AuthenticatedAdminEmployeesIdRoute,
  AuthenticatedAdminRequestsIdRoute: AuthenticatedAdminRequestsIdRoute,
  AuthenticatedAdminEmployeesIndexRoute: AuthenticatedAdminEmployeesIndexRoute,
  AuthenticatedAdminRequestsIndexRoute: AuthenticatedAdminRequestsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConsentEducationRoute: typeof AuthenticatedConsentEducationRoute
  AuthenticatedConsentVideoRoute: typeof AuthenticatedConsentVideoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConsentEducationRoute: AuthenticatedConsentEducationRoute,
  AuthenticatedConsentVideoRoute: AuthenticatedConsentVideoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EventRegisterRoute: EventRegisterRoute,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
